name: molecule_kmers
version: "1.0"
author: Haynes Heaton <whheaton@gmail.com>
about: looks for kmers in molecules
args:
    - output:
        long: output
        short: o
        takes_value: true
        required: true
        help: output directory
    - paired_kmers:
        long: paired_kmers
        short: p
        takes_value: true
        required: false
        help: kmer pairs (usually heterozygous pairs) in tsv kmer1\tkmer2\tcount\tcount (kmer is reverse compliment canonicalized)
    - unpaired_kmers:
        long: u
        takes_value: true
        required: false
        help: unpaired kmers
    - txg_reads:
        long: txg_reads
        takes_value: true
        required: false
        help: 10x genomics linked read fofn in format R1_filename\ttrim\nR2_filename\ttrim
    - txg_barcodes:
        long: txg_barcodes
        required: false
        takes_value: true
        help: 10x genomics barcode whitelist
    - long_reads:
        long: long_reads
        takes_value: true
        required: false
        help: pacbio fofn
    - hic_reads:
        long: hic_reads
        required: false
        takes_value: true
        help: hic fofn R1/R2 interleaved
    - threads:
        short: t
        long: threads
        required: false
        takes_value: true
        help: max number of threads. currently only paralelized over fastqs (and not across techs)
    - kmer_size:
        short: k
        long: kmer_size
        required: true
        help: kmer_size
        takes_value: true
    - fasta:
        short: f
        required: false
        help: fasta file
        takes_value: true
